title: Cloud Architect Insight Story
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://github.com/graudis/graudis.github.io/blob/master" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: graudis # add your name
author-img: Penguin-logo-2.jpg # add your photo
about-author: I am a Linux / OpenSource / Public Cloud Enterprise Computing Architect Engineer. # add description
social-twitter: NA # add your Twitter handle
social-facebook: NA # add your Facebook handle
social-github: graudis # add your Github handle
social-linkedin: NA # add your Linkedin handle
social-email: graudis@gmail.com # add your Email address

# Disqus
# discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
